### ISSUE TITLE
it's possible to remove necessary css and break above-the-fold

### ISSUE THREAD

**Issue by leeoniya** [ABVanton200/critical-css-parser#1]
@ABVanton200 

```css
#card {
  position: absolute;
  top: 1000%;
}
```

this will probably remove this `#card` element, then drop its CSS and on the real page it will now (wrongly) appear above the fold.

i can't think of a solution to this. but you may want to mention that stuff like this can happen if elements are moved below the fold by css only.
